[package]
name = "svelte-path-finder"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "macros"]

[dependencies]
macros = { path = "./macros" }
pad-adapter = "0.1.1"
serde = { version = "1.0.209", features = ["derive"] }
urlencoding = "2.1.3"
